version: "2"

services:
  app:
    image: lap-www
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    ports:
      - 8888:80
    volumes:
      - .:/var/www/html/
    environment:
        DB_PORT: 3306
        DB_HOST: mysql
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mosjid_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  redis:
    image: redis:4-alpine
    ports:
      - 16379:6379
    volumes:
      - redis:/data
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8889:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql

volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"